### ISSUE TITLE
Compatibility with Julia v 1.10

### ISSUE THREAD

**Issue by iniyannatarajan** [torrance/Casacore.jl#10]
`Pkg.add("Casacore")` on Julia 1.10 fails due to both CxxWrap and libcasacorecxx_jll failing to build. This seems to be due at least to CxxWrap being restricted to version 0.12 in Project.toml. Independently, I can confirm that I can precompile CxxWrap version 0.14 on Julia 1.10 successfully, but not 0.12.

Would it be easy to release an updated version of Casacore that works with Julia 1.10?

Thanks!

**Comment by torrance** [comment]
@iniyannatarajan Thanks for creating the issue, I'll look at this tomorrow.

**Comment by torrance** [comment]
I'm struggling to get BinaryBuilder to rebuild both casacore_jll and casacorecxx_jll. I'll have to pin down the issues I'm encountering and reach out for some help.

**Comment by torrance** [comment]
casacore_jll needs to be rebuilt with updated FITSIO_jll dependency.

Waiting for this to be merged: https://github.com/JuliaPackaging/Yggdrasil/pull/8082

**Comment by david-macmahon** [comment]
It looks like that has been merged now.  I haven't used BinaryBuilder before, but is there anything I can do to help this process along?

**Comment by torrance** [comment]
I'm having issues getting things working with the updated CxxWrap module. I have opened a ticket there: https://github.com/JuliaInterop/CxxWrap.jl/issues/410

**Comment by torrance** [comment]
I've merged the 1.10 branch; waiting on Yggdrasil to accept my changes, and then push out the changes to the Julia registry.

**Comment by torrance** [comment]
The Juliahub registry has been updated.

Install v0.3.0 of Casacore to work with Julia 1.10. There are no other changes to the module.
