### ISSUE TITLE
Allow empty index as shortcut for all colons

### ISSUE THREAD

**Issue by david-macmahon** [torrance/Casacore.jl#4]
Indexing into a column to get all data currently requires using as many colons (or `1:N` UnitRanges) as there are dimensions.  As a convenience, it would be nice if one could use empty indexing to get all data.  This also avoids having to know the dimensionality of the data, which can aid exploration of the data format.

Instead of:
```julia
antpos = table.ANETNNA[:POSITION][:,:]
```
one could use:
```Julia
antpos = table.ANETNNA[:POSITION][]
```
FWIW, HDF5.jl uses this convention to read data from HDF5 Datasets.

**Comment by torrance** [comment]
This is in dev now, and will be in v0.2 when released.

**Comment by david-macmahon** [comment]
Awesome, thanks!
